"""User Session table

Revision ID: 0cfa825b5452
Revises: ca596a97897d
Create Date: 2020-05-24 19:27:11.936051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0cfa825b5452'
down_revision = 'ca596a97897d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_data',
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('expire', sa.DateTime(), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user_data.id_'], ),
    sa.PrimaryKeyConstraint('id_'),
    sa.UniqueConstraint('session_id')
    )


def downgrade():
    op.drop_table('session_data')
    # ### end Alembic commands ###
