"""Access levels model

Revision ID: ca596a97897d
Revises: 8a328e754220
Create Date: 2020-01-31 12:42:44.503079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca596a97897d'
down_revision = '8a328e754220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    als = op.create_table('access_levels',
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('access_level', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_'),
    sa.UniqueConstraint('name')
    )

    op.bulk_insert(als, [
        {'name': 'admin', 'access_level': 0, 'description': 'Administrative privileges'},
        {'name': 'user', 'access_level': 1, 'description': 'Normal user'}
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_levels')
    # ### end Alembic commands ###
